language: go
go:
- 1.13
env:
- GO111MODULE=on
before_deploy:
- make release
- tar cvfz binaries.tar.gz bin/* -C bin .
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: Zg5ZMo0AM5m0Pm6DfSQO2WSynT7Y0qp9esFc5QgqViwo7Fl3VBQTnabocFHlRrGgTE0ssI0HDAB6xjiVph4WW9YsssSdNBUFGgiDhUnl6VOBedMSb/zIYHGoOo3gG4YNuE3Cxa/qVwd8IK3xsmiIM3PFVOWL7etsc7V5zfrReL9f9zfJ+0n1yw/2FYStli679Ml1BxWPtK3JHbpZpt27SrUmNOz/RF3BVBWFLu4NzMkiyiSEGLSshCHB21yoJ/+TeWsO4M0PXVuX73FxMlXcrRWMbDWKAOMQcb9yPqeQjKKkuvgs4JNK/lMP+E+gXBpFW171oFSwKhURmqhgXCn4PQj7hNbGq9rtKh6lsC8b2541M5/WV41PztSBDIrkQyIFogpvXHOG2pABWgEM+XrdS9EsAlsROEzz/dNZ/COOOTvfo9eqDROON6Ts5/IihjIZh3vW+hLJnM78Qii+YDw1Yq3qjMUt9JWIGwlkOtGxIgEjH9QbK913q+tBDvSNq+jggBzM2Z/f9lYRFfxn3rZgf8TTEGCm6g/CQqNQdbN2bsBGBf/306PN0PoeC9TSxRzi+Zzuv2sdqWCkeReDMUuXK8rAaBGVdfnCv+vD8dvun0+CZ/vqcwnzz6MaB8ZRs2BtD9XnwCztl5slgYjIfcrNfumUWaVTVW85G6PKkYEzg9s=
  file: binaries.tar.gz
  on:
    tags: true
