language: go
go:
- 1.11
env:
- GO111MODULE=on
before_deploy:
- make release
- tar cvfz binaries.tar.gz bin/* -C bin .
deploy:
  provider: releases
  api_key:
    secure: aJIehYqmEUQTN5tdRQhOvPsbgBoKvkxsJTBUfF+Hc7RPQC45z+rNNxXV99OUZm5pr7t1BUOnIIo8tZdUVsfPfWPHtFOpagmU62lojUG2PM0oCQ8CxV0HvwcFsdD4iINSN51lEVCtBZhtUEWBwoostvek1bouFKNjpzwYMRKFulvbxiLCrmi17wy+8sqkmbt+22uGyopsJtI4YrMIpW5EWYx7aHgQsvHZZEhyLDQ4EFfIBBj+53KJUHzY4/pIdasLVAOg8bADuzZ/e2AshyH5dtIQARrv00/sIhUvSx7Z1LZ0JZs+u8o3Jwsl4wQCW2X7LECApuFet4OenBPRLTjGKzP5uEK7IzPOqTqzgnOMt7/66MqaSizicbuHhwk4VCEYwP2ccEzOkNRRUngvxbyM0DbiUlpxw+qvAHrNeFNCFt1xkITgu68k+p1LsbUU0jFgbfMrVhJh2G3i9k6fx46k7n5L8vohCMv5Dc2LzemQzluYXoiDlj40HqUK57x/pXuYYpQxJMdP/lBkd3dSJSMV4CGwmOMuyHflniKW/aJ83C0JxkhhMh7yKk89YGerLoHxon5MVjz+IFhP1cUCTgxcMUjWozaua43QHwT0XTZhhDYHsMd3uddlDc9gJYyGQHzxJ094pns4XvM+ciKK79RORExbYGpQM6esJzycyhGToug=
  file: binaries.tar.gz
  on:
    tags: true
